<?php
session_start();
include("../connections.php");

if(isset($_SESSION["email"])){
    $email = $_SESSION["email"];

    $authention = mysqli_query($connections, "SELECT * FROM tbl_user WHERE email='$email'");
    $fetch = mysqli_fetch_assoc($authention);
    $account_type = $fetch["account_type"];

    if($account_type !=1){
        echo "<script>window.location.href='../Forbidden';</script>";
        exit;
    }
}

// use the user's nav/sidebar markup for the admin page
include("../User/nav.php");
// load user dashboard styles to match user nav/sidebar, then admin styles for admin-specific tweaks
echo '<link rel="stylesheet" href="../User/user-dashboard.css">';
echo '<link rel="stylesheet" href="admin-index.css">';

// inject admin sidebar menu (replace .sidebar-nav generated by user nav)
echo '<script>
document.addEventListener("DOMContentLoaded", function(){
    var sidebar = document.querySelector(".sidebar-nav");
    if (!sidebar) return;
    sidebar.innerHTML = `
        <a href="index.php" class="nav-item">
            <i class="fas fa-table"></i>
            <span>View Records</span>
        </a>
        <a href="PendingApprovals.php" class="nav-item">
            <i class="fas fa-briefcase"></i>
            <span>Pending Business</span>
        </a>
        <a href="PendingSubscriptions.php" class="nav-item">
            <i class="fas fa-file-invoice-dollar"></i>
            <span>Pending Subscription</span>
        </a>
		<a href="retriever.php" class="nav-item">
            <i class="fas fa-file-invoice-dollar"></i>
            <span>View Users</span>
        </a>
        <a href="Analytics.php" class="nav-item">
            <i class="fas fa-chart-line"></i>
            <span>Analytics</span>
        </a>
    `;
    // mark current page active
    var path = window.location.pathname.split("/").pop();
    sidebar.querySelectorAll(".nav-item").forEach(function(a){
        var href = a.getAttribute("href");
        if (href === path || (href === "index.php" && (path === "" || path === "index.php"))) {
            a.classList.add("active");
        } else {
            a.classList.remove("active");
        }
    });
});
</script>';

// Fetch metrics
$total_business_users = 0;
$pending_regs = 0;
$pending_subs = 0;
$total_earnings = 0.00;

$res = mysqli_query($connections, "SELECT COUNT(*) AS cnt FROM tbl_user WHERE account_type = 2");
if ($r = mysqli_fetch_assoc($res)) $total_business_users = intval($r['cnt']);

$res = mysqli_query($connections, "SELECT COUNT(*) AS cnt FROM tbl_pending_users WHERE account_type = 'pending'");
if ($r = mysqli_fetch_assoc($res)) $pending_regs = intval($r['cnt']);

$res = mysqli_query($connections, "SELECT COUNT(*) AS cnt FROM tbl_user WHERE subscription_proof IS NOT NULL AND subscription_approved = 0");
if ($r = mysqli_fetch_assoc($res)) $pending_subs = intval($r['cnt']);

$res = mysqli_query($connections, "SELECT IFNULL(SUM(total_cost),0) AS tot FROM tbl_purchase WHERE status='paid'");
if ($r = mysqli_fetch_assoc($res)) $total_earnings = floatval($r['tot']);

// Get recent pending users (limit 5)
$pending_list = [];
$plist = mysqli_query($connections, "SELECT id_pending, first_name, middle_name, last_name, establishment_name, sabang_location, lot_street_business FROM tbl_pending_users WHERE account_type='pending' ORDER BY id_pending DESC LIMIT 5");
while ($row = mysqli_fetch_assoc($plist)) {
    $pending_list[] = $row;
}
?>

<!-- Replace the main area with a user-style dashboard -->
<main class="main-content">
	<!-- Welcome / Hero -->
	<div class="welcome-card">
		<div class="welcome-content">
			<h1>Welcome back, <?php echo htmlspecialchars($fetch['first_name'] ?? 'Admin'); ?></h1>
			<p class="welcome-text">Manage pending businesses, subscription approvals and platform analytics from here.</p>
			<div class="business-info">
				<span>Total Business Users: <strong><?php echo $total_business_users; ?></strong></span>
				<span>Pending Business: <strong><?php echo $pending_regs; ?></strong></span>
				<span>Pending Subs: <strong><?php echo $pending_subs; ?></strong></span>
			</div>
		</div>
		<div class="welcome-image">
			<i class="fas fa-user-shield"></i>
		</div>
	</div>

	<!-- Stats Grid -->
	<div class="stats-grid">
		<div class="stat-card">
			<div class="stat-icon"><i class="fas fa-users"></i></div>
			<div class="stat-content">
				<h3><?php echo $total_business_users; ?></h3>
				<p>Business Users</p>
			</div>
		</div>

		<div class="stat-card">
			<div class="stat-icon"><i class="fas fa-briefcase"></i></div>
			<div class="stat-content">
				<h3><?php echo $pending_regs; ?></h3>
				<p>Pending Business</p>
			</div>
		</div>

		<div class="stat-card">
			<div class="stat-icon"><i class="fas fa-file-invoice"></i></div>
			<div class="stat-content">
				<h3><?php echo $pending_subs; ?></h3>
				<p>Pending Subscriptions</p>
			</div>
		</div>

		<div class="stat-card">
			<div class="stat-icon"><i class="fas fa-peso-sign"></i></div>
			<div class="stat-content">
				<h3>₱<?php echo number_format($total_earnings,2); ?></h3>
				<p>Total Earnings</p>
			</div>
		</div>
	</div>

	<!-- Actions Grid -->
	<div class="actions-section">
		<h2><i class="fas fa-tools"></i> Quick Actions</h2>
		<div class="actions-grid">
			<a href="PendingApprovals.php" class="action-card">
				<div class="action-icon"><i class="fas fa-user-check"></i></div>
				<div class="action-content">
					<h3>Pending Business</h3>
					<p>Review and approve new business registrations.</p>
				</div>
				<div class="action-arrow"><i class="fas fa-chevron-right"></i></div>
			</a>

			<a href="PendingSubscriptions.php" class="action-card">
				<div class="action-icon"><i class="fas fa-file-invoice-dollar"></i></div>
				<div class="action-content">
					<h3>Pending Subscriptions</h3>
					<p>Verify proof of payment and approve subscriptions.</p>
				</div>
				<div class="action-arrow"><i class="fas fa-chevron-right"></i></div>
			</a>

			<a href="retriever.php" class="action-card">
				<div class="action-icon"><i class="fas fa-users"></i></div>
				<div class="action-content">
					<h3>View Records</h3>
					<p>Manage user and business records.</p>
				</div>
				<div class="action-arrow"><i class="fas fa-chevron-right"></i></div>
			</a>

			<a href="Analytics.php" class="action-card">
				<div class="action-icon"><i class="fas fa-chart-line"></i></div>
				<div class="action-content">
					<h3>Analytics</h3>
					<p>View revenue and activity reports.</p>
				</div>
				<div class="action-arrow"><i class="fas fa-chevron-right"></i></div>
			</a>
		</div>
	</div>

	<!-- Recent Pending Registrations -->
	<div class="recent-section card">
		<div class="section-header">
			<h2><i class="fas fa-user-clock"></i> Recent Pending Registrations</h2>
			<a href="PendingApprovals.php" class="view-all-btn">View all</a>
		</div>

		<?php if (empty($pending_list)): ?>
			<div class="no-activity card">
				<i class="fas fa-check-circle" style="font-size:24px;opacity:.6;"></i>
				<p style="margin-top:8px;">No pending registrations at this time.</p>
			</div>
		<?php else: ?>
			<div class="activity-list">
				<?php foreach ($pending_list as $p):
					$first = trim($p['first_name'] ?? '');
					$middle = trim($p['middle_name'] ?? '');
					$last = trim($p['last_name'] ?? '');
					$full = htmlspecialchars(ucfirst($first) . ($middle !== '' ? ' ' . strtoupper($middle[0]) . '. ' : ' ') . ucfirst($last));
					$est = htmlspecialchars($p['establishment_name'] ?? 'N/A');
					$loc_part1 = trim($p['sabang_location'] ?? '');
					$loc_part2 = trim($p['lot_street_business'] ?? '');
					$loc = htmlspecialchars(trim($loc_part1 . ' ' . $loc_part2));
					$id_pending = intval($p['id_pending'] ?? 0);
					$approve_url = "PendingApprovals.php?id_pending={$id_pending}&approve=1";
					$reject_url = "PendingApprovals.php?id_pending={$id_pending}&reject=1";
				?>
				<div class="activity-item card">
					<div style="display:flex; align-items:center; gap:12px;">
						<div class="activity-icon">
							<i class="fas fa-briefcase"></i>
						</div>
						<div class="activity-content">
							<p style="margin:0;"><strong><?php echo $full; ?></strong></p>
							<small class="text-muted"><?php echo $est; ?><?php if ($loc) echo ' — ' . $loc; ?></small>
						</div>
					</div>

					<div style="margin-left:auto; display:flex; gap:8px; align-items:center;">
						<a href="<?php echo $approve_url; ?>"
						   class="btn-approve"
						   onclick="return confirm('Approve <?php echo addslashes($full); ?>?');"
						   title="Approve">
						   <i class="fas fa-check"></i>
						</a>

						<a href="<?php echo $reject_url; ?>"
						   class="btn-reject"
						   onclick="return confirm('Reject <?php echo addslashes($full); ?>?');"
						   title="Reject">
						   <i class="fas fa-times"></i>
						</a>
					</div>
				</div>
				<?php endforeach; ?>
			</div>
		<?php endif; ?>
	</div>
</main>

<!-- ensure icons load -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">